### ISSUE TITLE
Generalize the Tpl and HTML combinators to arbitrary content types

### ISSUE THREAD

**Issue by alpmestan** [alpmestan/servant-ede#1]
[ede](http://hackage.haskell.org/package/ede) itself isn't restricted to any content type, so _servant-ede_ shouldn't be either. This issue is for discussing a clean solution to this problem.

There's one tricky detail to keep in mind though: we might still want to be able to have content-type specific things happen. I intend to add XSS-sanitization for HTML template rendering very soon so a solution to make the combinators general should still allow for this.

**Comment by alpmestan** [comment]
Alright, @jkarni and I have discussed this a bit and the conversation resulted in what I believe to be a pretty sweet solution.

Let's wipe out `Tpl` and `HTML` as they are now. And just define this:

``` haskell
data Tpl (ct :: *) (file :: Symbol)

-- the filename doesn't matter for the content type,
-- as long as 'ct' is a valid one (html, json, css, application-specific, whatever really)
instance Accept ct => Accept (Tpl ct file) where
  accept _ = accept ctproxy
    where ctproxy = Proxy :: Proxy ct

instance (KnownSymbol file, Accept ct, ToObject a) => MimeRender (Tpl ct file) a where
  mimeRender _ val = -- call toObject on val and send it to the template
```

On top of that I can define a newtype for `HTML` that would XSS-sanitize the `Object`s before passing them to the templates. Or an overlapping instance by just defining a dummy `HTML` type and using it as `ct` above.

Thoughts?

**Comment by jkarni** [comment]
Looks good to me. Minor point: maybe `Ede` rather than `Tpl` for the datatype?

**Comment by alpmestan** [comment]
`Tpl` seems clearer on the meaning (to me) so it gets my vote.
