### ISSUE TITLE
Changing the bounds on dependencies on Hackage

### ISSUE THREAD

**Issue by fixingcredit** [alpmestan/servant-ede#5]
Hi @alpmestan, 

I wanted to use `servant-ede-0.51` with `servant-0.7` and `aeson-0.11.2` but I could not find a build plan due to the bounds set on Hackage. I was able to download the source and include it in my project and everything works fine. 

The `.cabal` file does not seem specify any upper bounds so not sure how the Hackage dependencies are determined. It will be great if you could update Hackage when you get a chance (unless there are specific reasons for the restriction). It will be nice to include it as a separate library than inside my source code. 

Thanks!

**Comment by alpmestan** [comment]
Hi @fixingcredit 
Thanks for the report. I've modified the bounds on hackage, can you try again now?

**Comment by fixingcredit** [comment]
Thanks, @alpmestan. I still get an error even though Hackage website seems to be updated. I am using `stack` and it could a caching issue? I will try again tomorrow. 

Sorry I missed `http-types` and `semigroups` in my previous note. I see `aeson`, `servant` and `vector` bounds are updated on Hackage.

```
--  Failure when adding dependencies:
      aeson: needed (>=0.8 && <0.10), 0.11.2.0 found (latest applicable is 0.9.0.1)
      http-types: needed (>=0.8 && <0.9), 0.9 found (latest applicable is 0.8.6)
      semigroups: needed (>=0.16 && <0.17), 0.18.1 found (latest applicable is 0.16.2.2)
      servant: needed (>=0.4 && <0.6), 0.7.1 found (latest applicable is 0.5)
      vector: needed (>=0.9 && <0.11), 0.11.0.0 found (latest applicable is 0.10.12.3)
    needed for package: servant-ede-0.5.1
```

**Comment by alpmestan** [comment]
Are you trying to install it via `cabal`? If yes, have you issued a `cabal update` before re-trying to install `servant-ede`?

**Comment by fixingcredit** [comment]
I am using `stack` and I did `stack update` before building. After giving it a night's rest, the cache has propagated. The new error is expected as the dependencies on Hackage has stricter bounds on these two

```
--  Failure when adding dependencies:
      http-types: needed (>=0.8 && <0.9), 0.9 found (latest applicable is 0.8.6)
      semigroups: needed (>=0.16 && <0.17), 0.18.1 found (latest applicable is 0.16.2.2)
    needed for package: servant-ede-0.5.1
```

Is it possible to update those two bounds as well -- it works for me with those versions listed but I don't really know if there are other issues to consider. 

Thanks very much!

**Comment by alpmestan** [comment]
Oops, forgot these two. I've updated the bounds for them. As far as I can tell, servant-ede should build fine with all these updated bounds but let me know if you encounter any problem (i.e if servant-ede's code needs fixing)!

Cheers =)

**Comment by fixingcredit** [comment]
Thank you, it works now! I have an issue with my template not picking up my field but that's probably an `EDE` issue and I will investigate further or report a reproducible example. I will close this issue.

**Comment by alpmestan** [comment]
Feel free to open an issue for your problem, even if it's not related to `servant-ede` itself, I might be able to help.

**Comment by fixingcredit** [comment]
Thanks for offering to help! 

I was able to find out the root cause of the issue -- I did not realize `ToObject` uses `ToJSON`'s field names and since I was using `fieldLabelModifier` inside `ToJSON` instance, I had to use the names post modification.
