### ISSUE TITLE
Creating a custom filter

### ISSUE THREAD

**Issue by fixingcredit** [alpmestan/servant-ede#6]
Hi @alpmestan 

Everything has been working smoothly so far wit `servant-ede` and thanks for your quick help with the Hackage changes. 

I wanted to add some custom filters that will turn  String / Text values into HTML formats that I can insert. Looking at this code: https://github.com/brendanhay/ede/blob/develop/src/Text/EDE/Internal/Filters.hs it seems like there is a way to define a function that can operate on Text inputs and return a modified Text.

I am not sure how I would go about creating such a custom filter and how to integrate it with `servant-ede`. Any help will be appreciated. 

Thanks!

**Comment by alpmestan** [comment]
Hello.

Sorry I left this ticket unanswered for so long! Got a newborn here who's been requiring all of my free time =)

Constructing filters involves [those types](http://hackage.haskell.org/package/ede-0.2.8.4/docs/Text-EDE-Filters.html#g:10). I haven't needed to write any myself, however you can look at the existing ones to get an idea on how to proceed: https://github.com/brendanhay/ede/blob/develop/src/Text/EDE/Internal/Filters.hs

This would require servant-ede to be changed: it should use `renderWith` instead of `render`, to make the additional filters available. If you're still interested in making this happen, we can give this a shot sometimes soon.

**Comment by fixingcredit** [comment]
@alpmestan  first of, congrats! Thanks for making the time to respond -- I can imagine how challenging it will be to make time for other things with a newborn. 

I have been traveling myself so been slower to respond. I decided to use Handlebars as a temporary fix. However, I will be interested in a finding a way to make it work with servant-ede. When I trying to figure this out I was looking at the `Filters.hs` to figure out how to add additional ones but did not really understand how to hook `renderWith` in servant-ede.

My Haskell knowledge is very, very limited so appreciate your guidance on what's the best way to go about changing to use `renderWith`.

**Comment by alpmestan** [comment]
If you write the rest of the code, I'm sure I can find a (worst case) hacky way to make this work with servant-ede.

**Comment by fixingcredit** [comment]
@alpmestan It has taken me so long to create a standalone example of something that we can use to test `renderWith` in servant-ede.  

I tried searching for `render` in `servant-ede` but I did not find any reference to it so I am not sure how to modify `loadTemplates` so it can optionally take a HashMap. It will be nice if `loadTempaltes` had a `Maybe HashMap`  as one of the params so it can use either `render` or `renderWith` depending on the value passed in. 

```
{-# LANGUAGE DataKinds                  #-}
{-# LANGUAGE TypeOperators              #-}
{-# LANGUAGE FlexibleInstances          #-}
{-# LANGUAGE OverloadedStrings          #-}
{-# LANGUAGE DeriveGeneric              #-}
{-# LANGUAGE DeriveAnyClass             #-}

module Main where

import Servant
import Servant.EDE 
import Text.EDE -- (render, fromPairs, Result(..),parse)
import Text.EDE.Filters ((@:),Term)
import qualified Data.HashMap.Strict as Map
import Data.Aeson (ToJSON, Object, (.=))
import Network.Wai
import GHC.Generics (Generic)
import Network.Wai.Handler.Warp (run)
import Data.ByteString (ByteString)
import Data.Text (Text, chunksOf)
import qualified Data.Text.Internal.Lazy as LT
import Control.Monad.Reader (liftIO,lift, liftM)

type API =       "users" :> Get '[JSON] [User] 
            :<|> "user"  :> Get '[JSON, HTML "user.tpl"] User 

data User = User { name :: String , email :: String } deriving (Generic, ToJSON)
instance ToObject User 

users :: [User] 
users = [User "Joe Smith" "joe@example.com", User "Jane Smith" "jane@example.com"] 

user :: User 
user = head users 

userAPI :: Proxy API
userAPI = Proxy

server :: Server API
server = return users :<|> return user 

app :: Application
app = serve userAPI server

v1 = "var"    :: Text 
w1 = "Hello"  :: Text
v2 = "values" :: Text 
l2 = [1,2,3]  :: [Int]
env = fromPairs [ v1 .= w1, v2 .= l2 ] :: Object

cfns :: Map.HashMap Text Term
cfns = Map.fromList ["toChars" @: (chunksOf 1)]

main :: IO ()
main = do
    let et   = eitherParse tmpl 
        tmpl = "{{var | toChars | show }}" :: ByteString
        t    = case et of
                 Left e -> error $ "Error"  ++ show e
                 Right tm -> tm
    print $ show $ renderWith cfns t env 
    loadTemplates userAPI "./templates"
    run 8081 app

```

**Template file**

```
<html>
<body>
  <ul>
    <li><strong>Name:</strong> {{ name }}</li>
    <li><strong>Age:</strong> {{ email }}</li>
  </ul>
</body>
</html>
```

**Cabal file** 

```
name:                ede-custom
version:             0.1.0.0
license:             BSD3
build-type:          Simple
cabal-version:       >=1.10

executable ede-custom
  hs-source-dirs:      src
  main-is:             Main.hs
  build-depends:       base        >= 4.7 && < 5
                     , aeson >= 0.11.1.4 && < 0.12
                     , bytestring >= 0.10.6.0 && < 0.11
                     , ede >= 0.2.8.4 && < 0.3 
                     , mtl >= 2.1 && < 2.3
                     , servant     >= 0.5 && < 1
                     , servant-server >= 0.5 && < 1
                     , servant-ede >= 0.5 && < 1
                     , text >=1.2.1.2 && < 2.0
                     , unordered-containers >= 0.2.5 && < 0.3
                     , wai >= 3.0 && < 3.4
                     , warp >= 3.0.13 && < 3.3
  ghc-options:  -O0
  default-language:    Haskell2010

```

**Comment by alpmestan** [comment]
Yeah, we can definitely make `loadTemplates` take an additional argument for custom filters. Do you feel like putting a PR together or should I do it when I get a chance to?

Regarding where `render` is called, you can see it e.g [here](https://github.com/alpmestan/servant-ede/blob/master/src/Servant/EDE.hs#L193).

**Comment by fixingcredit** [comment]
Thanks, @alpmestan. I am still beginner in Haskell so appreciate some guidance. I will try to create a PR. 

I looked through the linked file and I think I need to do something like this: 
1. Update `loadTemplates` to take an additional param 
2. Create an MVar to store the custom functions
3. Read this MVar in the MimeRender instance and if it is `Just` then call `renderWith` otherwise call `render`. 

Does that sound right to you?

**Comment by alpmestan** [comment]
@fixingcredit it does, absolutely. One "nitpick": you could even reuse the MVar that contains the compiled templates, to store the additional filters in there as well, hence turning

``` haskell
newtype Templates = Templates (HashMap String Template)
```

into something like:

``` haskell
data Templates = Templates
  { templates :: HashMap String Template
  , filters :: HashMap Text Term
  }
```

That way, you don't even have to wrap it in `Maybe` and can simply use an empty hashmap to use no other filters than the standard ones.

**Comment by fixingcredit** [comment]
Thanks @alpmestan. I was thinking about reusing the existing MVar but I did not understand the impact wrt Semigroup, Monoid, etc. I will assume that will not be an issue. 

I was still thinking about Maybe but what you recommend makes more sense and it is easier.  Couple of questions on the design, if you don't mind:
1. Should the new param be a list of pairs instead of a HashMap so people can just pass in `[]` if they just want standard library? `loadTemplates` will call `fromList` 
2. Also, should we create a new `loadTemplatesWithFilters` function that actually takes the new param so it does not break existing code?

**Comment by alpmestan** [comment]
Re 1., yeah I guess it could save an import from users =) sounds good.
Re 2., to be honest I wouldn't worry about it. I'm not sure there are a lot of people out there using _servant-ede_, and just calling your PR a breaking change and bumping the major version number should be enough, people would be warned some breaking change happened and we could make clear what that change is in the changelog.

Sounds good to you?
